# Generated by Django 4.0 on 2022-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_descriere2_eveniment_artisti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveniment',
            name='Pret',
            field=models.IntegerField(null=True),
        ),
    ]
